# Generated by Django 4.2.7 on 2023-11-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0004_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='gender',
            field=models.CharField(choices=[('1', 'Boys'), ('2', 'Girls')], default='Boys', max_length=20),
        ),
    ]
