# Generated by Django 4.2.7 on 2023-12-04 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0010_alter_products_description_alter_products_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('deal', models.IntegerField(blank=True, null=True)),
                ('Offer_price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('order_status', models.CharField(choices=[('1', 'Pending'), ('2', 'Processed'), ('3', 'Shipped'), ('4', 'Delivered')], default='Pending', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstcryapp.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
