# Generated by Django 4.2.7 on 2023-12-07 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0016_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('house_name', models.CharField(max_length=500)),
                ('street_name', models.CharField(max_length=1000)),
                ('landmark', models.CharField(max_length=500)),
                ('pincode', models.BigIntegerField()),
                ('city', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(default='India', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
