# Generated by Django 4.2.7 on 2023-12-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0018_address_default_value_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='landmark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
