# Generated by Django 4.2.7 on 2024-02-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0021_rename_address_order_user_address_return_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='type',
            field=models.CharField(choices=[('shirt', '1'), ('pants', '2'), ('both', '3')], default='1', max_length=10),
        ),
    ]
