# Generated by Django 4.2.7 on 2024-02-20 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0025_variation_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='color',
        ),
    ]
