# Generated by Django 4.2.7 on 2024-02-20 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0028_remove_variation_colors_delete_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='variation',
        ),
    ]
