# Generated by Django 4.2.7 on 2024-02-20 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0031_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='color',
        ),
        migrations.DeleteModel(
            name='variation',
        ),
    ]
