# Generated by Django 4.2.7 on 2024-02-20 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0033_color_variation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='color',
        ),
    ]
