# Generated by Django 4.2.7 on 2024-02-20 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0035_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='colors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='firstcryapp.color'),
        ),
    ]
