# Generated by Django 4.2.7 on 2024-02-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0036_variation_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='length',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='necktype',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='sleevetype',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
