# Generated by Django 4.2.7 on 2024-02-21 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0037_products_length_alter_products_necktype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='firstcryapp.products'),
        ),
    ]
