# Generated by Django 4.2.7 on 2024-02-21 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0038_color_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='product',
        ),
    ]
