# Generated by Django 4.2.7 on 2024-03-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0043_remove_variation_product_products_varient'),
    ]

    operations = [
        migrations.CreateModel(
            name='brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=5000)),
                ('specs', models.CharField(blank=True, max_length=5000, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='com_logo')),
            ],
        ),
    ]
