# Generated by Django 4.2.7 on 2024-03-19 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0044_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='firstcryapp.brands'),
        ),
        migrations.AddField(
            model_name='products',
            name='waist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
