# Generated by Django 4.2.7 on 2024-03-27 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0045_products_brand_products_waist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='qnty',
        ),
    ]
