# Generated by Django 4.2.7 on 2024-03-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0047_cart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='whishlist',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
