# Generated by Django 4.2.7 on 2024-04-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0050_address_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='gender',
        ),
        migrations.AddField(
            model_name='categories',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
