# Generated by Django 4.2.7 on 2024-04-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0053_alter_categories_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='type',
            field=models.CharField(choices=[('shirt', '1'), ('pants', '2'), ('t-shirt', '3'), ('both', '4')], default='1', max_length=10),
        ),
    ]
