# Generated by Django 4.2.7 on 2024-04-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0055_rename_offer_price_order_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.RemoveField(
            model_name='order_items',
            name='user_address',
        ),
        migrations.AddField(
            model_name='order',
            name='user_address',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
