# Generated by Django 4.2.7 on 2024-04-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0059_croppedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croppedimage',
            name='file',
            field=models.ImageField(upload_to='images123'),
        ),
    ]
