# Generated by Django 4.2.7 on 2024-04-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0060_alter_croppedimage_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='croppedimage',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
