# Generated by Django 4.2.7 on 2024-04-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0061_croppedimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Processed'), ('3', 'Shipped'), ('4', 'Delivered'), ('5', 'Cancelled'), ('6', 'Returned')], default='Pending', max_length=50),
        ),
    ]
