# Generated by Django 4.2.7 on 2024-04-08 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0067_alter_return_product_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return_product',
            name='stock_status',
        ),
    ]
