# Generated by Django 4.2.7 on 2024-04-08 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0068_remove_return_product_stock_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='return_product',
        ),
    ]
