# Generated by Django 4.2.7 on 2024-04-08 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0069_delete_return_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='return_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='firstcryapp.order')),
            ],
        ),
    ]
