# Generated by Django 4.2.7 on 2024-04-08 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0071_return_product_product_return_product_stock_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return_product',
            name='product',
            field=models.ForeignKey(default='de', on_delete=django.db.models.deletion.CASCADE, to='firstcryapp.products'),
        ),
    ]
