# Generated by Django 4.2.7 on 2024-04-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0075_return_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return_order',
            name='date',
        ),
    ]
