# Generated by Django 4.2.7 on 2024-04-08 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0076_remove_return_order_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='return_order',
        ),
    ]
