# Generated by Django 4.2.7 on 2024-04-08 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0077_delete_return_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='return_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='firstcryapp.order')),
            ],
        ),
    ]
