# Generated by Django 4.2.7 on 2024-04-08 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0078_return_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='return_product',
        ),
    ]
