# Generated by Django 4.2.7 on 2024-04-08 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0080_return_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='return_product',
            name='return_order',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='firstcryapp.return_order'),
        ),
    ]
