# Generated by Django 4.2.7 on 2024-04-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0081_return_product_return_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return_order',
            name='status',
            field=models.CharField(choices=[('1', 'Returned'), ('2', 'Cancelled')], default='Returned', max_length=50),
        ),
    ]
