# Generated by Django 4.2.7 on 2024-04-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0085_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='min_amount',
            field=models.IntegerField(default=0),
        ),
    ]
