# Generated by Django 4.2.7 on 2024-04-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0086_coupon_min_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Processed'), ('3', 'Shipped'), ('4', 'Delivered'), ('5', 'Cancelled'), ('6', 'Returned'), ('7', 'Cancelled by Admin')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='return_order',
            name='status',
            field=models.CharField(choices=[('1', 'Returned'), ('2', 'Cancelled'), ('3', 'Cancelled by Admin')], default='Returned', max_length=50),
        ),
    ]
