# Generated by Django 4.2.7 on 2024-04-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0087_alter_order_order_status_alter_return_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='return_order',
            name='stock_status',
            field=models.BooleanField(default=False),
        ),
    ]
